// Atomic hello-world — the whole host.
//
// A from-scratch host needs ONLY the published @orchestral/* packages plus its
// own ai-sdk model instance (built with its own API key) and an adapter that
// bridges that instance to the orchestral `call` contract. That adapter is
// host territory — core / runtime / patterns never import a provider SDK — and
// for the AI SDK it ships as the leaf package `@orchestral/adapters-ai-sdk`,
// which `./ai-sdk-wiring` calls. Everything below the `OPENAI_API_KEY` check
// is the ~15 lines of wiring: registry → models → router → runtime → submitJob.

import { openai } from '@ai-sdk/openai'
import {
  type Artifact,
  PatternRegistry,
} from '@orchestral/core'
import { InMemoryJobStore } from '@orchestral/core/memory'
import { createDefaultCapabilityRouter } from '@orchestral/core/routing'
import {
  createTextToImagePattern,
  TEXT_TO_IMAGE_PATTERN_ID,
  type TextToImageOutput,
} from '@orchestral/patterns'
import { InlineRuntime } from '@orchestral/runtime'
import { createImageModels } from './ai-sdk-wiring'

if (!process.env.OPENAI_API_KEY) {
  console.error(
    'Missing OPENAI_API_KEY.\n' +
      'Export a key first, e.g.  export OPENAI_API_KEY=sk-...\n' +
      '(no key? run `pnpm --filter atomic-hello-world test` — the smoke test ' +
      'exercises the same wiring with a mock model and needs no key.)',
  )
  process.exit(1)
}

// 1. Register the atomic Pattern we want to dispatch. `registry.add` is generic
//    over the Pattern's I/O, so a fully-typed factory result drops straight in.
const registry = new PatternRegistry()
registry.register(createTextToImagePattern())

// 2. Declare which model serves text-to-image. The model instance is ours —
//    @ai-sdk/openai builds it from OPENAI_API_KEY in the environment.
//    `createImageModels` (./ai-sdk-wiring) packs it into the ModelCapability
//    envelope the router consumes, with `call` wired through ai-sdk.
const getModels = createImageModels([
  {
    provider: 'openai',
    modelId: 'gpt-image-1',
    model: openai.image('gpt-image-1'),
  },
])

// 3. Default router. No getCapabilityOrder → enablement gate off, so every
//    declared model is a routing candidate (fine for a single-model demo).
const router = createDefaultCapabilityRouter({ getModels })

// 4. In-process runtime over the zero-dependency in-memory JobStore. The
//    generated bytes do not ride in `job.output` — `assets[].url` is bounded,
//    so a multi-megabyte blob can never sit in a value a model or a transcript
//    might see — they arrive on the `job:artifact` event. `submitJob` resolves
//    only once the job is terminal, after every event has fired, so the
//    subscription is made from the creation hook.
const artifacts: Artifact[] = []
const runtime = new InlineRuntime({
  store: new InMemoryJobStore(),
  registry,
  router,
  onJobCreated: (jobId) =>
    runtime.subscribe(jobId, (ev) => {
      if (ev.type === 'job:artifact') artifacts.push(ev.artifact)
    }),
})

// 5. Dispatch. InlineRuntime runs synchronously in this tick — the awaited Job
//    is already `done`.
const job = await runtime.submitJob<{ prompt: string }, TextToImageOutput>({
  patternId: TEXT_TO_IMAGE_PATTERN_ID,
  input: { prompt: 'a red bicycle' },
})

if (job.status !== 'done' || !job.output) {
  console.error(`Dispatch did not complete: status=${job.status}`, job.error)
  process.exit(1)
}

const { assets, model, provider, latencyMs } = job.output
console.log(`Generated ${assets.length} image(s) via ${provider} (${model}) in ${latencyMs}ms`)
// `job.output.assets` is the inventory (placeholder ids + modality); the bytes
// are the artifacts collected above. A real host stores each one and stamps
// its own canonical id onto the matching asset.
for (const [i, artifact] of artifacts.entries()) {
  const preview =
    artifact.uri.length > 64 ? `${artifact.uri.slice(0, 64)}…` : artifact.uri
  console.log(`  [${i}] ${artifact.kind} (${artifact.mime ?? '?'}) — ${preview}`)
}
